# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base.yaml
  - /dataset: colmap
  - /initialization: colmap
  - _self_

dataset:
  train:

    ray_jittering:
      type: stratified              # Choose from: 'none', 'stratified', 'random'
      start_iteration: 3500         # Start jittering from iteration N
      num_samples: 16               # 'stratified' jittering only -- number of subsamples to use in pattern
      apply_every_n_iterations: 1   # 1 for applying every iteration, 2 for applying every other iteration
