# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base.yaml
  - /dataset: colmap
  - /initialization: colmap
  - _self_

enable_writer: true 
test_last: true 
use_wandb: true 
wandb_project: "3dgrt-dev" 

export_ingp:
  enabled: true
  force_half: false
  
model:
  densify:
    share_density: true 
    params: features_albedo 
    split_grad_threshold: 0.000007 
    relative_size_threshold: 0.0 
    end_iteration: 25000 
    
  prune:
    end_iteration: 30000 
    
  default_density: 0.5 

  reset_density:
    new_max_density: 0.5
     
dataset:
  downsample_factor: 4 
  
  train:
    ray_jittering.type: none
  
loss:
  lambda_reg_density: 0.1 

render:
  kernel_function: exp-p4-dist
  max_num_slabs: 1
  max_hit_per_slab: 16 
  train_hit_sampling: true

# overwrite of default parameters
val_frequency: 1095 