# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /apps/test_ingp.yaml
  - /dataset: colmap
  - /initialization: colmap
  - _self_

dataset:
  downsample_factor: 2


