# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /apps/ncore
  - /background@_global_: sky_mlp
  - _self_

# overwrite of default parameters
num_workers: 16
checkpoint:
  frequency: 1000