# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base.yaml
  - /dataset: nerf
  - /initialization: random
  - _self_

# overwrite of default parameters
dataset:
  train:
    sample_full_image: True

model:
  background:
    name: background-color
    color: black
