# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

variables:
  PYTHON_VERSION: "3.11"
  FF_TIMESTAMPS: true # Enable timestamps in job logs
  GIT_CLEAN_FLAGS: -ffdx -e .keep
  CACHED_ZIP: "${CI_BUILDS_DIR}/.keep/nerf_example_data.zip"
  REMOTE_ZIP: "http://cseweb.ucsd.edu/~viscomp/projects/LF/papers/ECCV20/nerf/nerf_example_data.zip"
  TARGET_SHA: "ce4e94e031c099a19ef04cfb6c71f1e47225d97d365be610b476e379a386c25f"

workflow:
  auto_cancel:
    on_new_commit: interruptible
  rules:
    # Those rules follow this logic:
    # Phase 1: No open merge request, user pushes to a branch: --> Run branch pipeline
    # Phase 2: Open merge request: --> Do not run branch pipeline, but run merge result pipeline
    # Phase 3: Open merge request, user pushes to the branch: --> Re-run merge result pipeline
    # Phase 4: Branch is merged into protected branch: --> Run branch pipeline
    #
    # Additionally we do not allow auto-cancel of outdated pipelines on protected branches, we want to collect all
    # possible data points on these post-merge pipelines.
    - if: $CI_COMMIT_REF_PROTECTED == "true" # Run branch pipeline on protected branches (main or release)
      auto_cancel:
        on_new_commit: none
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Run merge request or merge result pipelines (if merge result pipelines are configured in gitlab)
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE != "web" # Do not run branch pipelines if merge request is open, but still allow web use
      when: never
    - if: $CI_COMMIT_BRANCH # Run branch pipelines for all branches when triggered by a branch push and no merge request is open
      auto_cancel:
        on_new_commit: none

stages:
  - setup
  - build
  - benchmark

.download_dataset: &download_dataset
  - |
    echo "Downloading NeRF Synthetic Lego"
    mkdir -p "${CI_BUILDS_DIR}/.keep"
    echo "${TARGET_SHA}  ${CACHED_ZIP}" | sha256sum -c --quiet 2>/dev/null \
      || wget ${REMOTE_ZIP} -O "${CACHED_ZIP}"
    unzip -o "${CACHED_ZIP}" "nerf_synthetic/lego/*" -d "${CI_BUILDS_DIR}/data"

.gpu_job: &gpu_job
  interruptible: true
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
  tags:
    - 1_gpu
    - arch/x86_64
    - colossus
    - cuda_arch/86
    - docker
    - gpu
    - os/linux
    - type/docker

nightly:
  <<: *gpu_job
  image: ubuntu:24.04
  stage: setup
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $NIGHTLY_JOB == "1"
  script:
    - echo "Running nightly build..."

lint-code:
  <<: *gpu_job
  image: ubuntu:24.04
  stage: setup
  before_script:
    - |
      echo "Install prerequisites ..."
      apt-get update
      apt-get install -y --no-install-recommends build-essential \
        ca-certificates curl wget git python3-pip
    - |
      echo "Install black and isort ..."
      pip install --break-system-packages "black==25.9.0" "isort==5.13.0"
  script:
    - |
      echo "Checking code formatting..."
      bash formatter.sh --check
      echo "Done."

build-conda:
  <<: *gpu_job
  image: ubuntu:24.04
  stage: build
  parallel:
    matrix:
      - CONDA_CUDA_VERSION:
        - "11.8"
        - "12.8"
  before_script:
    - nvidia-smi -L
    - |
      echo "Install prerequisites ..."
      apt-get update
      apt-get install -y --no-install-recommends build-essential ca-certificates \
        curl wget git unzip libglib2.0-0 libgl1 libxcb1 gcc-11 g++-11
    - |
      echo "Install conda ..."
      curl -sSL -o /tmp/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-$(uname -m).sh
      export PATH=/opt/conda/bin:$PATH
      export NVCC_PREPEND_FLAGS=""
      bash /tmp/miniconda.sh -b -p /opt/conda && rm -f /tmp/miniconda.sh
      conda install -y python=${PYTHON_VERSION}
      conda clean -ya
      conda config --append channels conda-forge
    - |
      echo "Install UV"
      curl -LsSf https://astral.sh/uv/install.sh | sh
      source $HOME/.local/bin/env
  script:
    - |
      echo "Install CONDA environment"
      git config --global --add safe.directory "/builds/nrs/3dgrut-internal"
      CUDA_VERSION=${CONDA_CUDA_VERSION} bash ./scripts/create_conda.sh 3dgrut
    - |
      echo "Install 3DGRUT"
      conda run -n 3dgrut ./install_env_uv.sh 3dgrut
    - *download_dataset
    - |
      echo "Test training 3DGRT and 3DGUT"
      conda run -n 3dgrut python train.py --config-name apps/nerf_synthetic_3dgrt.yaml \
        path=${CI_BUILDS_DIR}/data/nerf_synthetic/lego out_dir=runs experiment_name=lego_3dgrt n_iterations=100
      conda run -n 3dgrut python train.py --config-name apps/nerf_synthetic_3dgut.yaml \
        path=${CI_BUILDS_DIR}/data/nerf_synthetic/lego out_dir=runs experiment_name=lego_3dgut n_iterations=100

build-uv:
  <<: *gpu_job
  stage: build
  image: nvidia/cuda:${UV_CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}
  parallel:
    matrix:
      - UV_CUDA_VERSION: "11.8.0"
        UBUNTU_VERSION: "22.04"
      - UV_CUDA_VERSION: "12.8.1"
        UBUNTU_VERSION: "24.04"
      - UV_CUDA_VERSION: "13.0.2"
        UBUNTU_VERSION: "24.04"
  before_script:
    - nvidia-smi -L
    - |
      echo "Install prerequisites ..."
      apt-get update
      apt-get install -y --no-install-recommends build-essential ca-certificates \
        curl wget git unzip libglib2.0-0 libgl1 libxcb1 
    - |
      echo "Install UV"
      curl -LsSf https://astral.sh/uv/install.sh | sh
      source $HOME/.local/bin/env
  script:
    - |
      echo "Install 3DGRUT"
      bash ./install_env_uv.sh
      source .venv/bin/activate
    - *download_dataset
    - |
      echo "Test training 3DGRT and 3DGUT"
      python train.py --config-name apps/nerf_synthetic_3dgrt.yaml \
        path=${CI_BUILDS_DIR}/data/nerf_synthetic/lego out_dir=runs experiment_name=lego_3dgrt n_iterations=100
      python train.py --config-name apps/nerf_synthetic_3dgut.yaml \
        path=${CI_BUILDS_DIR}/data/nerf_synthetic/lego out_dir=runs experiment_name=lego_3dgut n_iterations=100

# benchmark-3dgut:    # This job runs in the deploy stage.
#   stage: benchmark  # It only runs when *both* jobs in the test stage complete successfully.
#   script:
#     - echo "Running benchmarks..."
#     - echo "Benchmarks successfully completed."

# benchmark-3dgrt:    # This job runs in the deploy stage.
#   stage: benchmark  # It only runs when *both* jobs in the test stage complete successfully.
#   script:
#     - echo "Running benchmarks..."
#     - echo "Benchmarks successfully completed."
