model:
  lambda_background: 0.05 # NRE uses 0.05
  background:
    name: sky-mlp
    dir_encoding_config:
      otype: SphericalHarmonics
      degree: 4
    mlp_network_config:
      otype: FullyFusedMLP
      activation: ReLU
      output_activation: Sigmoid
      n_neurons: 64
      n_hidden_layers: 2
    device: 'cuda'
    composite_in_linear_space: false
