path: ???
experiment_name: ""
resume: ""
n_iterations: 30000
with_gui: false

dataset:
  type: colmap
  
initialization_method: point_cloud      # one of [colmap, point_cloud, random]

model:
  density_activation: sigmoid
  scale_activation: exp
  optimize_density: true
  optimize_features: true
  optimize_position: false
  optimize_rotation: false
  optimize_scale: false
  bvh_update_frequency: 1
  densify:
    frequency: 100
    start_iteration: 500
    end_iteration: 15000
    grad_threshold: 0.0002
    relative_size_threshold: 0.01 # Gaussians larger than relative_size_threshold * scene_extent will be split not cloned
    split:
      n_gaussians: 2
  prune:
    frequency: 100
    start_iteration: 500
    end_iteration: 15000
    density_threshold: # All Gaussians with the density lower than this will be pruned away
  reset_density:
      frequency: 100
      start_iteration: 500
      end_iteration: 15000
      new_max_density: 0.01 # The density of the all the Gaussians will be set to min(density, this) 

checkpoint:
  frequency: 1000

optimizer:
  type: adam
  args:
  lr: 0.01
  eps: 1.e-15
  params:
    positions:
        lr: 0.01
    density:
        lr: 0.01
    features:
        lr: 0.01
    rotation:
        lr: 0.01
    scale:
        lr: 0.01
