path: ???
experiment_name: ""
resume: ""
n_iterations: 30000

dataset:
  type: colmap



model:
  density_activation: sigmoid
  scale_activation: exp
  optimize_density: true
  optimize_features: true
  optimize_position: false
  optimize_rotation: false
  optimize_scale: false
  bvh_update_frequency: 1
  densify_prune:
    frequency: 100
    start_iteration: 500
    end_iteration: 15000
    grad_threshold: 0.0002

checkpoint:
  frequency: 1000

with_gui: false

optimizer:
  type: adam
  args:
  lr: 0.01
  eps: 1.e-15
  params:
    positions:
        lr: 0.01
    density:
        lr: 0.01
    features:
        lr: 0.01
    rotation:
        lr: 0.01
    scale:
        lr: 0.01
