path: ???
experiment_name: ""
resume: ""
out_dir: "runs"
n_iterations: 30000
with_gui: false
val_frequency: 100
num_workers: 8

dataset:
  type: nerf
  downsample_factor: 1  # for datasets that include multi-scale versions of images [colmap]
  
  train:
    batch_size: 8192
    sample_full_image: True
  
initialization:
  method: random      # one of [colmap, point_cloud, random]
  num_gaussians: 100_000   # method=random only: number of initial gaussians to use

model:
  density_activation: sigmoid
  scale_activation: exp
  optimize_density: true
  optimize_features_albedo: true
  optimize_features_specular: true
  optimize_position: true
  optimize_rotation: true
  optimize_scale: true
  bvh_update_frequency: 1
  progressive_training:
    feature_type: 'sh'        # one of [sh, mlp], currently only sh supported
    init_n_features: 0        # sh: initial sh deg | mlp: num of dims initially unmasked
    max_n_features: 3 # 3         # sh: maximum sh deg | mlp: total num of dims finally unmasked
    increase_frequency: 1000  # unmask more feature dimensions every N global steps
    increase_step: 1          # sh: how many degrees unmasked per step | mlp: how many dims unmasked per step

  lambda_background: 0.
  background:
    name: background-color
    color: black

  densify:
    frequency: 100 # densification_interval in 3DGS with default value 100
    start_iteration: 500 # densify_from_iter in 3DGS default value 500
    end_iteration: 15000 # densify_until_iter in 3DGS default value 15_000
    clone_grad_threshold: 0.0002 # Called densify_grad_threshold in 3DGS with default value 0.0002
    split_grad_threshold: 0.0002 # Called densify_grad_threshold in 3DGS with default value 0.0002
    relative_size_threshold: 0.01 # Gaussians larger than relative_size_threshold * scene_extent will be split not cloned. Called percent_dense in 3DGS with default value 0.01
    split:
      n_gaussians: 2 # Hardcoded to 2 in 3DGS

  # They use the same values for pruning and densification so check the above values
  prune:
    frequency: 100
    start_iteration: 500
    end_iteration: 15000
    density_threshold: 0.01 # All Gaussians with the density lower than this will be pruned away

  # Start and end iteration are not used in 3DGS
  reset_density:
    frequency: 3000 # Opacity reset interval in 3DGS default value 3000
    start_iteration: 0
    end_iteration: ${n_iterations}
    # This parameter is hardcoded in the 3DGS to 0.01
    new_max_density: 0.01 # The density of the all the Gaussians will be set to min(density, this) 

checkpoint:
  frequency: 1000

optimizer:
  type: adam # We only support adam for now
  lr: 0.01
  eps: 1.e-15
  params:
    positions:
      lr: 0.00016 # 3DGS value: 0.00016 initial and decayed to 0.00016
    density:
      lr: 0.05 # 3DGS value: 0.05
    features_albedo:
      lr: 0.0025 # 3DGS value: 0.0025
    features_specular:
      lr: ${div:${optimizer.params.features_albedo.lr},20} # 3DGS value 20x smaller than lr of features_albedo
    rotation:
      lr: 0.001 # 3DGS value: 0.001
    scale:
      lr: 0.005 # 3DGS value: 0.005
    background:
      lr: 0.01

scheduler:
  positions:
    # In the 3DGS paper they additionally have a parameter lr_delay_mult, but is is not being used so I drop it here
    type: exp
    lr_init: ${optimizer.params.positions.lr}
    lr_final: 0.000016
    max_steps: ${n_iterations}

  density:
    type: skip

render:
  hit_mode : 0
  max_hit_per_slab: 32
  max_num_slabs: 64
  topk_hits: False
  patch_size: 1
  sph_degree: 3
  gaussian_sigma_threshold: 3.0
  min_transmittance: 0.03
