
name = "3dgrt_app"
description = "Running our 3D gaussian ray tracing code."
# This command is run before any other specified commands (see README)
#    Note: workspace_path is pulled from the `[ngc.workspace.path]` value
#          end this command with `;` as additional commands will be appended
base_command = "cd {workspace_path}/experiments/{exp_name}; . ./ngc/ngc_pre_job.sh; "

[ngc]
name = "3dgrt.notamodel.3dgrt_app"
open_ports = [6006, 8888]
result_path = "/result"

[ngc.ace]
id = 257
name = "nv-us-west-2"
instance = "ovxa40.48g.1"

# Can mount more by adding more `[ngc.workspaceXYZ]` categories
# but this one will be used by the local workspace commands
[ngc.workspace]
path = "/workspace"
id = "3dgrt_workspace_west"
mode = "RW"

[docker]
team = "nvidian/ct-toronto-ai"
name = "3dgrt"
